# Copyright (c) YugaByte, Inc.

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-universe-boot-script
  labels:
    app: {{ template "yugaware.name" . }}
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Values.helm2Legacy | ternary "Tiller" (.Release.Service | quote) }}
data:
  universe_boot_script: |
{{ tpl (.Values.yugaware.universe_boot_script) . | indent 4 }}
